# This is a basic workflow to help you get started with Actions

name: CI


on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Run a one-line script
        run: mvn package
      - name: tomcat deploy
        run: curl -v -u admin:admin -T  /home/runner/work/spring3-mvc-maven-xml-hello-world/spring3-mvc-maven-xml-hello-world/target/spring3-mvc-maven-xml-hello-world-1.0-SNAPSHOT.war 'http://ec2-3-110-132-63.ap-south-1.compute.amazonaws.com:8081//master/text/deploy?path=/githubaction_tomcat_spring&update=true'  
